### ISSUE TITLE
Add function annotations to existing python client code.

### ISSUE THREAD

**Issue by kmehant** [scorelab/BassaClient#23]
It would be great if we can have python function annotations added to our existing python client code.
Reference: [Link](https://mypy.readthedocs.io/en/stable/introduction.html)

**Comment by kritikaparmar-programmer** [comment]
Hey @kmehant , can you explain this a bit more, I want to contribute..

**Comment by kmehant** [comment]
@kritikaparmar-programmer 
Good to see you here. Just look at our python codebase on this repo and we need to add metadata to the functions for better visibility. 
I have added a  couple of links for reference look at here 
https://mergeurl.com/v/3aqRL
